apiVersion: apps/v1
kind: Deployment
metadata:
   name: app-dep
spec:
   replicas: {{ .Values.rep  }}
   selector:
     matchLabels:
       {{ .Values.tag }}: {{ .Values.key }}
   minReadySeconds: {{ .Values.mrs }}
   template:
     metadata:
      Labels:
        {{ .Values.tag }}: {{ .Values.key }}
     spec:
       containers:
       {{- include myapp | indent 7 }}

