apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-myapp
spec:
  selector:
    {{ .Values.tag }}: {{ .Values.key }}
  type: NodePort
  ports:
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30001
